import type { ReductionTip } from '../types';

export const REDUCTION_TIPS: ReductionTip[] = [
  {
    id: 'tip-1',
    category: 'transport',
    title: 'Switch to public transit',
    description: 'Taking the bus instead of driving cuts emissions by over 50%. Trains are even better, producing roughly 80% less CO2 per km than a car.',
    potentialSavingKg: 4.5,
    difficulty: 'easy',
  },
  {
    id: 'tip-2',
    category: 'transport',
    title: 'Cycle for short trips',
    description: 'Replace car journeys under 5 km with cycling. This eliminates emissions entirely for those trips and improves your health.',
    potentialSavingKg: 1.0,
    difficulty: 'easy',
  },
  {
    id: 'tip-3',
    category: 'transport',
    title: 'Carpool to work',
    description: 'Sharing a ride with one other person halves per-person transport emissions. Use workplace boards or apps to find carpool partners.',
    potentialSavingKg: 3.0,
    difficulty: 'medium',
  },
  {
    id: 'tip-4',
    category: 'food',
    title: 'Have one meatless day per week',
    description: 'Replacing a beef meal with a vegetarian option once a week saves roughly 6 kg CO2 per week. Start with a day that works for your schedule.',
    potentialSavingKg: 5.9,
    difficulty: 'easy',
  },
  {
    id: 'tip-5',
    category: 'food',
    title: 'Choose chicken over beef',
    description: 'When you do eat meat, chicken produces less than half the emissions of beef per serving. Swapping two beef meals a week for chicken makes a real difference.',
    potentialSavingKg: 3.6,
    difficulty: 'easy',
  },
  {
    id: 'tip-6',
    category: 'food',
    title: 'Reduce food waste',
    description: 'Plan meals, store food properly, and use leftovers. The average household throws away 30% of purchased food, wasting all the emissions from its production.',
    potentialSavingKg: 2.5,
    difficulty: 'medium',
  },
  {
    id: 'tip-7',
    category: 'energy',
    title: 'Switch to LED lighting',
    description: 'LED bulbs use 75% less energy than incandescent bulbs and last 25 times longer. Replace your five most-used lights first for the biggest impact.',
    potentialSavingKg: 0.5,
    difficulty: 'easy',
  },
  {
    id: 'tip-8',
    category: 'energy',
    title: 'Lower your thermostat by 1 degree',
    description: 'Reducing heating by just 1 degree Celsius can cut your heating energy use by up to 10%. Wear a warmer layer indoors instead.',
    potentialSavingKg: 3.0,
    difficulty: 'easy',
  },
  {
    id: 'tip-9',
    category: 'energy',
    title: 'Switch to a green energy provider',
    description: 'Renewable electricity tariffs can reduce your electricity emissions to near zero. Many providers now offer competitive green tariffs.',
    potentialSavingKg: 8.0,
    difficulty: 'hard',
  },
  {
    id: 'tip-10',
    category: 'shopping',
    title: 'Buy second-hand clothing',
    description: 'Thrift stores and online resale platforms let you find quality clothing without the emissions of new manufacturing. Each item saves roughly 10 kg CO2.',
    potentialSavingKg: 10.0,
    difficulty: 'easy',
  },
  {
    id: 'tip-11',
    category: 'shopping',
    title: 'Repair electronics instead of replacing',
    description: 'Extending the life of a laptop or phone by even one year significantly reduces its annualized carbon footprint. Look for local repair cafes or manufacturer repair programs.',
    potentialSavingKg: 25.0,
    difficulty: 'medium',
  },
  {
    id: 'tip-12',
    category: 'shopping',
    title: 'Bring reusable bags for groceries',
    description: 'Using reusable bags eliminates the need for single-use plastic or paper bags. Keep them by your door or in your car so you never forget.',
    potentialSavingKg: 0.5,
    difficulty: 'easy',
  },
];
